language: php

php:
- 7.1

sudo: false


env:
  global:
    - PLUGIN_NAME=FroshAdminer

script:
- "./build.sh"


stages:
  - test
  - name: Store-Check
    if: tag IS blank AND env(PLUGIN_ID) IS present AND type != pull_request
  - name: Store-Sync
    if: branch = master AND env(PLUGIN_ID) IS present AND type != pull_request
  - name: Store-Deploy
    if: tag IS present

jobs:
  include:
    - stage: Store-Check
      php: 7.3
      before_script: skip
      install:
        - chmod +x ./build.sh
        - ./build.sh ${TRAVIS_BRANCH}
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/frosh-plugin-upload.phar?raw=true' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:validate ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip
    - stage: Store-Sync
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/frosh-plugin-upload.phar?raw=true' -O frosh-plugin-upload.phar
      script:
        - php frosh-plugin-upload.phar plugin:update ${TRAVIS_BUILD_DIR}/Resources/store
    - stage: Store-Deploy
      before_script: skip
      php: 7.3
      install:
        - wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/blob/master/frosh-plugin-upload.phar?raw=true' -O frosh-plugin-upload.phar
      script:
        - chmod +x ./build.sh
        - ./build.sh
        - php frosh-plugin-upload.phar plugin:upload ${TRAVIS_BUILD_DIR}/${PLUGIN_NAME}*.zip

deploy:
  provider: releases
  api_key:
    secure: U2OcY4bAhmo+eoRJ6UJE2uRkPyx+FVpnqCYO9JvJKrNiEgrxttQLyUszz/wVjJ9or4doUyWQ2B2qsmzZHJZDT8nxG9MIbEy/F4ppJdOE0+pbRj3YXDlJp/BsrctyIq8mDMD93h43fBnl06Wyyx4AQDmrvZr0u+kqviVEh7nRgVar0UiUc7pWNCxUAebIvDE9mbBdktdHnfjCQ7Wq0Y/N1CMLeBw9W8LZiurnk5e629WWJcVkfiVaEQGCCxLVBcjpyjXJXUnoewcMPzLvEBK0HdCyWcy8cPiDKvQz/ll5Aut5x8GZlkLc2PoPOJNtgC93CavZq1N0wvlVr4a1qCw8utshrjD6m9d04jVFjfgtpkJrloMTPOxrOR0VbPf8PvzhRQUYHHSpB4wmZEBR0otnNRhxj+eUD46+NLQpSutIoQ78gKHeuT6GdS2REh6PZ/JphMubmTAb502ONfCOtiC6GOz2smAoeN5c9/eCJag9yYdtU/2OqJ3a6dJM/isua5G7Edq/KBy4pXXk8+9jK21kQ6VjAENHn5D1Yh6edf0EDWIdZRcdppyk3OyGqoLhqCF7yoRpz36cBpqTBk5XLmNwgfsaPvaGTLhBhwbCx7S0dIzVkYSMABK2ftQi+2p1nRPe71dIe46/w0etvdFXwjXiuCYE+DPoIN2NE9mjnp+6PzY=
  file: FroshAdminer-*.zip
  file_glob: true
  on:
    tags: true
